// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValidateIrasId.Infrastructure;

#nullable disable

namespace ValidateIrasId.Infrastructure.Migrations
{
    [DbContext(typeof(HarpProjectDataDbContext))]
    [Migration("20250821104946_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ValidateIrasId.Application.DTO.HarpProjectRecord", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(150)")
                        .HasDefaultValueSql("CAST(NEWID() AS VARCHAR(150))");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullResearchTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IrasId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSyncDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecID")
                        .HasColumnType("int");

                    b.Property<string>("RecName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortStudyTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyDecision")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IrasId")
                        .IsUnique();

                    b.ToTable("HarpProjectRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
